// Regenerates the auto-updated regions of README.md.
//
// Usage: node scripts/update-profile.mjs
// Run daily by .github/workflows/update-readme.yml.
//
// Each region updates independently. If a fetch failed, that region keeps
// whatever it already contained — a stale number beats a broken card.

import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import {
  fetchRepos, fetchProfile, fetchLanguageTotals, fetchContributions,
  computeStreaks, sumStars,
} from "./lib/github.mjs";
import {
  replaceRegion, badgeImg, renderRecentRepos, renderStatBadges, renderLanguageBars,
} from "./lib/render.mjs";

const USER = "MacroMaster101";
const README = "README.md";
const GENERATED = "<!-- Generated by scripts/update-profile.mjs. Do not edit by hand. -->";

// Repos that already have a hand-written card in the Featured Projects table.
// Keep in sync with that table in README.md so the auto-generated Latest
// Activity feed does not repeat them.
const FEATURED = [
  "mazora-network",
  "vero_saloon_website",
  "travel_genie",
  "travel_genie_app",
  "denguerisk",
  "web-voting-system",
];

export function buildReadme(readme, data) {
  const warnings = [];
  let text = readme;

  // Assert every marker pair exists before writing anything, so a structural
  // break fails loudly instead of half-updating the document.
  for (const name of ["FOLLOWERS-BADGE", "REPOS-BADGE", "RECENT-REPOS", "STATS", "LANGS"]) {
    replaceRegion(text, name, "");
  }

  const region = (name, source, render) => {
    if (source === null || source === undefined) {
      warnings.push(`Skipped ${name}: no data`);
      return;
    }
    text = replaceRegion(text, name, render());
  };

  // FOLLOWERS-BADGE and REPOS-BADGE both come from the profile fetch, so a
  // missing profile is one failure, not two: warn once and leave both marker
  // regions untouched, rather than firing a duplicate warning per badge.
  if (data.profile === null || data.profile === undefined) {
    warnings.push("Skipped profile badges: no data");
  } else {
    text = replaceRegion(text, "FOLLOWERS-BADGE",
      badgeImg({ label: "FOLLOWERS", message: String(data.profile.followers), color: "6e40c9", logo: "github", alt: "Follower count" }));
    text = replaceRegion(text, "REPOS-BADGE",
      badgeImg({ label: "REPOS", message: String(data.profile.public_repos), color: "6e40c9", logo: "git", alt: "Public repository count" }));
  }

  region("RECENT-REPOS", data.repos, () =>
    `\n${GENERATED}\n\n${renderRecentRepos(data.repos, { exclude: ["macromaster101", ...FEATURED] })}\n\n`);

  // STATS draws on three sources. If ANY is missing the whole region is
  // skipped: rendering `0 stars` because the repo fetch failed would be a
  // confident wrong number, which is worse than a stale correct one.
  const statsReady =
    data.contributions && data.repos && data.profile ? data.contributions : null;

  region("STATS", statsReady, () => {
    const { current, longest } = computeStreaks(data.contributions.days);
    return `\n${renderStatBadges({
      stars: sumStars(data.repos),
      repos: data.profile.public_repos,
      commits: data.contributions.totalCommits,
      prs: data.contributions.totalPRs,
      currentStreak: current,
      longestStreak: longest,
    })}\n`;
  });

  region("LANGS", data.langTotals, () => `\n${renderLanguageBars(data.langTotals)}\n`);

  return { text, warnings };
}

/** Resolves to the value, or null with a warning — never rejects. */
async function attempt(label, promise) {
  try {
    return await promise;
  } catch (err) {
    console.warn(`WARN ${label}: ${err.message}`);
    return null;
  }
}

async function main() {
  const [repos, profile, contributions] = await Promise.all([
    attempt("repos", fetchRepos(USER)),
    attempt("profile", fetchProfile(USER)),
    attempt("contributions", fetchContributions(USER)),
  ]);
  const langTotals = repos ? await attempt("languages", fetchLanguageTotals(repos)) : null;

  const readme = await readFile(README, "utf8");
  const { text, warnings } = buildReadme(readme, { repos, profile, contributions, langTotals });
  for (const w of warnings) console.warn(`WARN ${w}`);

  if (text === readme) {
    console.log("README already up to date.");
    return;
  }
  await writeFile(README, text, "utf8");
  console.log("README updated.");
}

// Only run when invoked directly, so the test can import buildReadme freely.
// pathToFileURL is the Windows-safe way to compare a CLI path to import.meta.url.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error(err.message);
    process.exit(1);
  });
}
